name: campbell
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ca-certificates=2021.10.8
  - libcxx=12.0.1
  - libffi=3.4.2
  - libjpeg-turbo=2.1.1
  - libzlib=1.2.11
  - ncurses=6.3
  - openssl=3.0.0
  - pip=21.3.1
  - python=3.8.12
  - python_abi=3.8
  - readline=8.1
  - setuptools=60.5.0
  - sqlite=3.37.0
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zbar=0.10
  - zlib=1.2.11
  - pip:
    - asgiref==3.5.0
    - backports-zoneinfo==0.2.1
    - cachetools==5.0.0
    - certifi==2021.10.8
    - charset-normalizer==2.0.10
    - dj-database-url==0.5.0
    - django==4.0.1
    - google-api-core==2.4.0
    - google-api-python-client==2.36.0
    - google-auth==2.4.1
    - google-auth-httplib2==0.1.0
    - googleapis-common-protos==1.54.0
    - gunicorn==20.1.0
    - httplib2==0.20.2
    - idna==3.3
    - pillow==9.0.0
    - protobuf==3.19.3
    - psycopg2-binary==2.9.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.7
    - pyzbar==0.1.8
    - requests==2.27.1
    - rsa==4.8
    - six==1.16.0
    - sqlparse==0.4.2
    - uritemplate==4.1.1
    - urllib3==1.26.8
    - whitenoise==5.3.0
