# Generated by Django 4.0.1 on 2022-01-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('chi_name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('SP', 'Soup'), ('OT', 'Others')], default='SP', max_length=2)),
            ],
        ),
    ]
