# Generated by Django 4.0.1 on 2022-01-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chi_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
