# Generated by Django 4.0.1 on 2022-01-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_reader', '0002_alter_product_chi_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
