# Generated by Django 4.0.1 on 2022-01-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_reader', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
