# Generated by Django 4.0.1 on 2022-01-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_reader', '0004_remove_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
